/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package papeleria;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Cristianss
 */
public class Vendedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendedores
     */
    public Vendedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreVendedor = new javax.swing.JLabel();
        txtNombreVendedor = new javax.swing.JTextField();
        txtSexoVendedor = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        lblDomicilioVendedor = new javax.swing.JLabel();
        txtDomicilioVendedor = new javax.swing.JTextField();
        lblCorreoVendedor = new javax.swing.JLabel();
        txtCorreoVendedor = new javax.swing.JTextField();
        lblContraseñaVendedor = new javax.swing.JLabel();
        txtContraseñaVendedor = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        imgVendedor = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        Backgroun = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblNombreVendedor.setText("Nombre :");
        getContentPane().add(lblNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, -1));

        txtNombreVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, -1));

        txtSexoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtSexoVendedor.setText("Sexo :");
        getContentPane().add(txtSexoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 50, -1));

        txtSexo.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, -1));

        lblDomicilioVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblDomicilioVendedor.setText("Domicilio :");
        getContentPane().add(lblDomicilioVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, -1));

        txtDomicilioVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtDomicilioVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, -1));

        lblCorreoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblCorreoVendedor.setText("Correo :");
        getContentPane().add(lblCorreoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 50, -1));

        txtCorreoVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtCorreoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 140, -1));

        lblContraseñaVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblContraseñaVendedor.setText("Contraseña :");
        getContentPane().add(lblContraseñaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        txtContraseñaVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtContraseñaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 140, -1));

        lblID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        lblID.setText("ID :");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 20, -1));

        txtID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 70, -1));

        imgVendedor.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        imgVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil (1).png"))); // NOI18N
        getContentPane().add(imgVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 130, 130));

        btnBuscar.setBackground(new java.awt.Color(227, 95, 30));
        btnBuscar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, -1));

        btnAgregar.setBackground(new java.awt.Color(227, 95, 30));
        btnAgregar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 70, -1));

        Backgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoVendedores.png"))); // NOI18N
        getContentPane().add(Backgroun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Conexion conn = Conexion.getInstancia();
        PreparedStatement ps;
        ResultSet rs; //Guardar resultado de una consulta
        String consultaSQL="SELECT NombreVendedor,SexoVendedor, DomicilioVendedor, CorreoVendedor, ContrasenaVendedor FROM Vendedores WHERE idVendedor=?;";
        try
        {
        conn.Conectar();
        ps=conn.cadena.prepareStatement(consultaSQL);
        ps.setInt(1,Integer.valueOf(txtID.getText()));
        rs=ps.executeQuery();
        if(rs.next())
        {
            txtNombreVendedor.setText(rs.getString(1));
            txtSexo.setText(rs.getString(2));
            txtDomicilioVendedor.setText(rs.getString(3));
            txtCorreoVendedor.setText(rs.getString(4));
            txtContraseñaVendedor.setText(rs.getString(5));
        }
            else
            JOptionPane.showMessageDialog(null, "No se encontro el vendedor  :( ");
        ps.close();
        rs.close();
        conn.Desconectar();
        conn.cadena.close();
        
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            finally
            {
            ps=null;
            rs=null;
            conn=null;
            }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion conn = Conexion.getInstancia();
        PreparedStatement ps;
        String consultaSQL;
        consultaSQL = "INSERT INTO Vendedores(NombreVendedor,SexoVendedor, DomicilioVendedor, CorreoVendedor, ContrasenaVendedor,ImagenVendedor, activo)\n";
        consultaSQL +="VALUES(?,?,?,?,?,?,?)";
        try
        {
        conn.Conectar();
        ps=conn.cadena.prepareStatement(consultaSQL);
        ps.setString(1,txtNombreVendedor.getText().trim());
        ps.setString(2, txtSexo.getText().trim());
        ps.setString(3, txtDomicilioVendedor.getText().trim()); 
        ps.setString(4, txtCorreoVendedor.getText().trim());
        ps.setString(5, txtContraseñaVendedor.getText().trim());
        ps.setString(6, "imagencolores.jpg");
        ps.setBoolean(7, true);
        ps.execute();
        JOptionPane.showMessageDialog(null, "El vendedor " +txtNombreVendedor.getText() + " fue registrado con éxito :)");
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
                                        

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroun;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel imgVendedor;
    private javax.swing.JLabel lblContraseñaVendedor;
    private javax.swing.JLabel lblCorreoVendedor;
    private javax.swing.JLabel lblDomicilioVendedor;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombreVendedor;
    private javax.swing.JTextField txtContraseñaVendedor;
    private javax.swing.JTextField txtCorreoVendedor;
    private javax.swing.JTextField txtDomicilioVendedor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JLabel txtSexoVendedor;
    // End of variables declaration//GEN-END:variables
}
